apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
spec:
  containers:
  - name: cont1
    image: nginx
    ports:
      - name: http
        protocol: TCP
        containersPort: 80
  -  name: cont2
     image: nginx
     ports:
       - name: http
         protocol: TCP
         containersPort: 88
